# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_server_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='node_type',
            field=models.CharField(choices=[(b'Gateway', b'Gateway'), (b'Service', b'Service')], default=b'Service', max_length=20),
        ),
    ]
