# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_auto_20200826_1125'),
        ('deploy', '0003_server_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='gateway',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.ApiGateway', verbose_name=b'Gateway'),
        ),
    ]
