# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-28 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0045_portal'),
        ('deploy', '0005_auto_20200826_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='portal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Portal', verbose_name=b'Gateway'),
        ),
    ]
