# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_server_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(default=b'Node1', max_length=100, unique=True, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='server',
            name='portal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Portal', verbose_name=b'Portal'),
        ),
    ]
