# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-31 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_server_gitlab_runner_register_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='gitlab_runner_auth_token',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='gitlab_runner_id',
            field=models.IntegerField(default=8080, verbose_name=b'Runner Id'),
        ),
        migrations.AlterField(
            model_name='server',
            name='gitlab_runner_register_token',
            field=models.CharField(blank=True, default=b'register_token', max_length=100),
        ),
    ]
