# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-31 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_auto_20200831_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='gitlab_runner_auth_token',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
