# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-30 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20200831_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'DeployName', max_length=100, unique=True, verbose_name=b'Name')),
                ('product_type', models.CharField(choices=[(b'WeiSite', b'WeiSite'), (b'WeiShop', b'WeiShop')], default=b'WeiShop', max_length=20)),
                ('location', models.CharField(choices=[(b'hangzhou', b'hangzhou')], default=b'hangzhou', max_length=20)),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('suffix', models.CharField(default=b'suffix', max_length=100, unique=True, verbose_name=b'Suffix')),
            ],
        ),
        migrations.AlterField(
            model_name='server',
            name='node_type',
            field=models.CharField(choices=[(b'MQ', b'MQ'), (b'Consul', b'Consul'), (b'Access', b'Access'), (b'Gateway', b'Gateway'), (b'Service', b'Service')], default=b'Service', max_length=20),
        ),
        migrations.AddField(
            model_name='server',
            name='deploy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Deploy', verbose_name=b'Deploy'),
        ),
    ]
