# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-30 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0011_auto_20201130_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='index',
            field=models.CharField(default=b'01', max_length=20),
        ),
        migrations.AlterField(
            model_name='server',
            name='node_type',
            field=models.CharField(choices=[(b'Access', b'Access'), (b'Service', b'Service'), (b'Gateway', b'Gateway'), (b'Consul', b'Consul'), (b'MQ', b'MQ'), (b'Portal', b'Portal'), (b'Mix', b'Mix')], default=b'Service', max_length=20),
        ),
    ]
