# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0012_auto_20201130_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='node_type',
            field=models.CharField(choices=[(b'Access', b'Access'), (b'Service', b'Service'), (b'Gateway', b'Gateway'), (b'Consul', b'Consul'), (b'MQ', b'MQ'), (b'APM', b'APM'), (b'Portal', b'Portal'), (b'Mix', b'Mix')], default=b'Service', max_length=20),
        ),
    ]
