# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0060_portal_api_gw_domain'),
        ('deploy', '0013_auto_20201201_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='service_provider',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.Consul', verbose_name=b'Consul'),
        ),
    ]
