# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-03 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0014_deploy_service_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[(b'WeiSite', b'WeiSite'), (b'WeiShop', b'WeiShop')], default=b'WeiShop', max_length=20)),
                ('node_type', models.CharField(choices=[(b'WeiSite', b'WeiSite'), (b'WeiShop', b'WeiShop')], default=b'Gateway', max_length=20)),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('ip', models.CharField(default=b'127.0.0.1', max_length=50, verbose_name=b'IP')),
                ('version', models.CharField(default=b'1.0.0', max_length=100, verbose_name=b'Version')),
                ('framework', models.TextField(verbose_name=b'Framwork')),
                ('deploy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='deploy.Deploy', verbose_name=b'Consul')),
            ],
        ),
    ]
