# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-03 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0016_auto_20201203_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='last_active_time',
            field=models.DateTimeField(auto_now=True, verbose_name=b'Last Active Time'),
        ),
        migrations.AddField(
            model_name='nodeinfo',
            name='up_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'Up Time'),
        ),
    ]
