# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-04 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0017_auto_20201203_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='up',
            field=models.BooleanField(default=False, verbose_name=b'No Up'),
        ),
    ]
