# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0060_portal_api_gw_domain'),
        ('deploy', '0018_nodeinfo_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='elastic_apm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.ElastAPM', verbose_name=b'ElasticAPM'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='event_bus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.EventBus', verbose_name=b'EventBus'),
        ),
    ]
