# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0019_auto_20201204_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='gateway_domain_name',
            field=models.CharField(default=b'gateway.marvelsystem.net', max_length=100, verbose_name=b'Gateway DomainName'),
        ),
    ]
