# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-05 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0063_remove_apigateway_port'),
        ('deploy', '0020_deploy_gateway_domain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='log_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.LogItemGroup', verbose_name=b'LogLevel'),
        ),
    ]
