# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-05 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0021_deploy_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='description',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description'),
        ),
    ]
