# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0022_deploy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='portal_domain_name',
            field=models.CharField(default=b'portal.marvelsystem.net', max_length=100, verbose_name=b'Portal DomainName'),
        ),
        migrations.AddField(
            model_name='deploy',
            name='website_domain_name',
            field=models.CharField(default=b'portal.marvelsystem.net', max_length=100, verbose_name=b'Website DomainName'),
        ),
    ]
