# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0023_auto_20201205_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='portal_admin_tag',
            field=models.CharField(default=b'v1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='deploy',
            name='portal_console_tag',
            field=models.CharField(default=b'v1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='deploy',
            name='portal_h5_tag',
            field=models.CharField(default=b'v1.0.0', max_length=20),
        ),
    ]
