# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-06 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0026_auto_20201205_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='env',
        ),
    ]
