# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-06 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0027_remove_server_env'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Node1', max_length=100, unique=True, verbose_name=b'Name')),
                ('ip', models.CharField(default=b'127.0.0.1', max_length=50, verbose_name=b'IP')),
                ('is_blocked', models.BooleanField(default=False, verbose_name=b'Blocked')),
            ],
        ),
    ]
