# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-06 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0028_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='deploy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deploy.Deploy', verbose_name=b'Deploy'),
        ),
        migrations.AlterField(
            model_name='server',
            name='gitlab_runner_id',
            field=models.IntegerField(default=None, null=True, verbose_name=b'Runner Id'),
        ),
    ]
