# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-07 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0029_auto_20201206_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='health_report',
            field=models.TextField(default=b'', verbose_name=b'Health Report'),
        ),
        migrations.AlterField(
            model_name='nodeinfo',
            name='framework',
            field=models.TextField(default=b'', verbose_name=b'Framework'),
        ),
    ]
