# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-07 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0031_auto_20201207_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeinfo',
            name='health_report',
            field=models.TextField(default=b'{}', verbose_name=b'Health Report'),
        ),
    ]
