# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-07 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0034_auto_20201207_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='node_name',
            field=models.CharField(choices=[('ActionLog', 'Service_ActionLog'), ('Aggregate', 'Service_Aggregate'), ('CMS', 'Service_CMS'), ('Comment', 'Service_Comment'), ('Common', 'Service_Common'), ('Favorite', 'Service_Favorite'), ('Logistics', 'Service_Logistics'), ('Manager', 'Service_Manager'), ('Market', 'Service_Market'), ('Media', 'Service_Media'), ('Member', 'Service_Member'), ('Merchant', 'Service_Merchant'), ('Notification', 'Service_Notification'), ('Open', 'Service_Open'), ('Order', 'Service_Order'), ('Partion', 'Service_Partion'), ('Payment', 'Service_Payment'), ('Points', 'Service_Points'), ('Product', 'Service_Product'), ('ShoppingCart', 'Service_ShoppingCart'), ('WeiXin', 'Service_WeiXin'), (b'APIGateway', b'Gateway_APIGateway'), (b'Admin', b'Portal_Admin'), (b'Console', b'Portal_Console'), (b'H5', b'Portal_H5')], default=b'APIGateway', max_length=20, verbose_name=b'Node Name'),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set([('deploy', 'node_type', 'node_name')]),
        ),
    ]
