# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-08 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0035_auto_20201207_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeinfo',
            old_name='node_service',
            new_name='node_name',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='portal_admin_tag',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='portal_console_tag',
        ),
        migrations.RemoveField(
            model_name='deploy',
            name='portal_h5_tag',
        ),
    ]
