# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-13 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0037_nodeinfo_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[(b'Portal', b'Portal'), (b'Gateway', b'Gateway'), (b'Service', b'Service')], default=b'Service', max_length=20, verbose_name=b'Node Type')),
                ('node_name', models.CharField(choices=[('ActionLog', 'Service_ActionLog'), ('Aggregate', 'Service_Aggregate'), ('CMS', 'Service_CMS'), ('Comment', 'Service_Comment'), ('Common', 'Service_Common'), ('Favorite', 'Service_Favorite'), ('Logistics', 'Service_Logistics'), ('Manager', 'Service_Manager'), ('Market', 'Service_Market'), ('Media', 'Service_Media'), ('Member', 'Service_Member'), ('Merchant', 'Service_Merchant'), ('Notification', 'Service_Notification'), ('Open', 'Service_Open'), ('Order', 'Service_Order'), ('Partion', 'Service_Partion'), ('Payment', 'Service_Payment'), ('Points', 'Service_Points'), ('Product', 'Service_Product'), ('ShoppingCart', 'Service_ShoppingCart'), ('WeiXin', 'Service_WeiXin'), (b'APIGateway', b'Gateway_APIGateway'), (b'Admin', b'Portal_Admin'), (b'Console', b'Portal_Console'), (b'H5', b'Portal_H5')], default=b'APIGateway', max_length=20, verbose_name=b'Node Name')),
                ('tag', models.CharField(default=b'v1.0.0', max_length=50, verbose_name=b'Tag')),
                ('version', models.CharField(default=b'1.0.0', max_length=50, verbose_name=b'Image Version')),
                ('db_version', models.CharField(default=b'20200101180500', max_length=50, verbose_name=b'DB Version')),
            ],
        ),
    ]
