# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-13 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0070_auto_20201213_1211'),
        ('deploy', '0039_delete_taginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='config.GitLabProject', verbose_name=b'Project'),
        ),
        migrations.AddField(
            model_name='version',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='config.TagInfo', verbose_name=b'Tag'),
        ),
    ]
