# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0042_weixinminiprogramtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='weixinminiprogramtemplate',
            name='latest_version',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
