# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0043_weixinminiprogramtemplate_latest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='weixin_miniprogram_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploys', to='deploy.WeiXinMiniprogramTemplate', verbose_name=b'WeiXin Miniprogram Template'),
        ),
    ]
