# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-17 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0044_deploy_weixin_miniprogram_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploy',
            name='weixin_miniprogram_template',
        ),
        migrations.DeleteModel(
            name='WeiXinMiniprogramTemplate',
        ),
    ]
