# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0073_auto_20201217_0954'),
        ('deploy', '0045_auto_20201217_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='weixin_miniprogram_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deploys', to='config.WeiXinMiniprogramTemplate', verbose_name=b'WeiXin Miniprogram Template'),
        ),
    ]
