# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-17 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0046_deploy_weixin_miniprogram_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='enable_node_info_filter',
            field=models.BooleanField(default=False, verbose_name=b'Node Info Filter'),
        ),
    ]
