# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0048_auto_20201217_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='apm_sample',
            field=models.BooleanField(default=False, verbose_name=b'APM Sample'),
        ),
    ]
