# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2021-01-22 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0075_apph5'),
        ('deploy', '0049_version_apm_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='app_domain_name',
            field=models.CharField(default=b'app.marvelsystem.net', max_length=100, verbose_name=b'App DomainName'),
        ),
        migrations.AddField(
            model_name='server',
            name='app',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.AppH5', verbose_name=b'App'),
        ),
    ]
