version: "3"
services:
  app:
    environment:
      - WEB_APP_PORT=80
      - WEB_APP_WORKERS=1
    image: mscmcwebsite_app:latest
    restart: always
    build: .  # '点'代表当前目录
    command: "sh start.sh" #"python manage.py runserver 0.0.0.0:80"
    volumes:
      - .:/app/bin/
    ports:
      - "80:80"