version: "3"
services:
  cmc.website:
    environment:
      - WEB_APP_PORT=8080
      - WEB_APP_WORKERS=1
    image: cms.website:latest
    restart: always
    build: .  # '点'代表当前目录
    command: "sh start.sh" #"python manage.py runserver 0.0.0.0:80"
    volumes:
      - /opt/ms-cmc.website/config:/app/config/ #将本地文件夹挂载到容器中的目录 用于提供程序运行的配置文件
      - /opt/ms-cmc.website/logs:/app/logs/ #将本地日志文件挂载到容器中的日志目录 用于外部查看程序运行日志
    ports:
      - "80:8080"