# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-01 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0052_auto_20200903_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Title', max_length=50, verbose_name=b'Title')),
                ('group_name', models.CharField(default=b'GroupName', max_length=50, verbose_name=b'Group Name')),
                ('description', models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Description')),
                ('name', models.CharField(default=b'Name', max_length=50, verbose_name=b'Name')),
                ('permission', models.IntegerField(default=0, verbose_name=b'Permission')),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='config.Service', verbose_name=b'Service')),
            ],
        ),
    ]
