# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-25 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_auto_20200825_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pipeline_trigger',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Pipeline Trigger'),
        ),
        migrations.AlterField(
            model_name='route',
            name='upstream_header_transform',
            field=models.ManyToManyField(blank=True, related_name='HeaderTransform', to='config.HeaderTransform'),
        ),
    ]
