# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0033_auto_20200825_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default=b'GroupName', max_length=50, verbose_name=b'GroupName')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
            ],
        ),
        migrations.CreateModel(
            name='SettingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(default=b'SettingKey', max_length=50, verbose_name=b'SettingKey')),
                ('setting_value', models.CharField(default=b'SettingValue', max_length=50, verbose_name=b'SettingValue')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
                ('setting_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.SettingGroup', verbose_name=b'SettingGroup')),
            ],
        ),
    ]
