# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0034_settinggroup_settingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='other_settings',
            field=models.ManyToManyField(to='config.SettingGroup', verbose_name=b'Other Settings'),
        ),
    ]
