# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0036_auto_20200826_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigateway',
            name='pipeline_trigger',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Pipeline Trigger'),
        ),
    ]
