# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0037_apigateway_pipeline_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigateway',
            name='elastic_apm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.ElastAPM', verbose_name=b'ElasticAPM'),
        ),
        migrations.AddField(
            model_name='apigateway',
            name='event_bus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.EventBus', verbose_name=b'EventBus'),
        ),
        migrations.AddField(
            model_name='apigateway',
            name='services',
            field=models.ManyToManyField(blank=True, to='config.Service', verbose_name=b'Used Services'),
        ),
    ]
