# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0038_auto_20200826_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigateway',
            name='other_settings',
            field=models.ManyToManyField(blank=True, to='config.SettingGroup', verbose_name=b'Other Settings'),
        ),
    ]
