# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0039_apigateway_other_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigateway',
            name='log_level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.LogItemGroup', verbose_name=b'LogLevel'),
        ),
    ]
