# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0040_apigateway_log_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigateway',
            name='port',
            field=models.IntegerField(default=8080, verbose_name=b'Http Port'),
        ),
    ]
