# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0041_apigateway_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingitem',
            name='is_array',
            field=models.BooleanField(default=False, verbose_name=b'Is Array'),
        ),
    ]
