# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-26 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0042_settingitem_is_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingitem',
            name='setting_value',
            field=models.CharField(default=b'SettingValue', max_length=1000, verbose_name=b'SettingValue'),
        ),
    ]
