# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-28 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0043_auto_20200826_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apigateway',
            name='is_default',
        ),
    ]
