# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0044_remove_apigateway_is_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Portal', max_length=50, verbose_name=b'Portal Name')),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('domain_name', models.CharField(default=b'dev-portal.marvelsystem.net', max_length=100, verbose_name=b'Domain Name')),
                ('admin_pipeline_trigger', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Admin Pipeline Trigger')),
                ('console_pipeline_trigger', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'console Pipeline Trigger')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
            ],
        ),
    ]
