# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-31 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0045_portal'),
    ]

    operations = [
        migrations.CreateModel(
            name='WXBoundServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Consul', max_length=50, verbose_name=b'Consul Name')),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('ip', models.CharField(default=b'127.0.0.1', max_length=50, verbose_name=b'IP')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
            ],
        ),
    ]
