# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-08-31 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0046_wxboundserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxboundserver',
            name='name',
            field=models.CharField(default=b'node-01', max_length=50, verbose_name=b'Consul Name'),
        ),
    ]
