# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-09-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0047_auto_20200831_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_scheme',
            field=models.CharField(choices=[(b'Consul', b'Consul'), (b'Host', b'Host'), (b'HostGroup', b'HostGroup')], default=b'Consul', max_length=20, verbose_name=b'Route Scheme'),
        ),
    ]
