# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-09-01 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0048_route_route_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitemgroup',
            name='env',
            field=models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20),
        ),
        migrations.AddField(
            model_name='settinggroup',
            name='env',
            field=models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='downstream_host',
            field=models.CharField(blank=True, default=b'dev-api.marvelsystem.net', max_length=255, null=True, verbose_name=b'DownstreamHost'),
        ),
        migrations.AlterField(
            model_name='route',
            name='downstream_port',
            field=models.CharField(blank=True, default=80, max_length=255, null=True, verbose_name=b'DownstreamPort'),
        ),
    ]
