# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-09-02 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0050_auto_20200901_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='downstream_host',
        ),
        migrations.RemoveField(
            model_name='route',
            name='downstream_port',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_scheme',
        ),
        migrations.RemoveField(
            model_name='service',
            name='port',
        ),
    ]
