# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0052_auto_20200903_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='h5_pipeline_trigger',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'H5 Pipeline Trigger'),
        ),
        migrations.AlterField(
            model_name='portal',
            name='console_pipeline_trigger',
            field=models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Console Pipeline Trigger'),
        ),
    ]
