# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-11 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0054_auto_20201111_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='merge_message',
            field=models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name=b'Merge Message'),
        ),
        migrations.AddField(
            model_name='portal',
            name='merge_success',
            field=models.BooleanField(default=True, verbose_name=b'Merge Success'),
        ),
    ]
