# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-12 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0055_auto_20201111_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='authentication_scheme',
            field=models.CharField(choices=[(b'NoAuth', b'NoAuth'), (b'Bearer', b'Bearer'), (b'JWT-Anonymous', b'JWT-Anonymous'), (b'HMAC', b'HMAC')], default=b'NoAuth', max_length=20, verbose_name=b'Auth Schema'),
        ),
    ]
