# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0056_auto_20201112_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='production_tag',
            field=models.CharField(default=b'v1.0.0', max_length=20),
        ),
    ]
