# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-30 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0058_portal_partion_info_api_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='admin_tag',
            field=models.CharField(default=b'v1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='portal',
            name='console_tag',
            field=models.CharField(default=b'v1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='portal',
            name='h5_tag',
            field=models.CharField(default=b'v1.0.0', max_length=20),
        ),
    ]
