# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0059_auto_20201130_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='api_gw_domain',
            field=models.CharField(blank=True, default=b'dev-api-gw.marvelsystem.net', max_length=1000, verbose_name=b'API Gateway'),
        ),
    ]
