# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-04 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0060_portal_api_gw_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='elastic_apm',
        ),
        migrations.RemoveField(
            model_name='service',
            name='event_bus',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_provider',
        ),
    ]
