# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-04 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0061_auto_20201204_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apigateway',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='apigateway',
            name='elastic_apm',
        ),
        migrations.RemoveField(
            model_name='apigateway',
            name='event_bus',
        ),
        migrations.RemoveField(
            model_name='apigateway',
            name='service_provider',
        ),
    ]
