# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-05 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0063_remove_apigateway_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logitemgroup',
            name='env',
        ),
    ]
