# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-05 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0064_remove_logitemgroup_env'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='api_gw_domain',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='partion_info_api_domain',
        ),
    ]
