# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-05 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0065_auto_20201205_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portal',
            name='admin_tag',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='console_tag',
        ),
        migrations.RemoveField(
            model_name='portal',
            name='h5_tag',
        ),
    ]
