# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0067_remove_service_production_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitLabProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default=b'platform/path', max_length=100, unique=True, verbose_name=b'Path')),
                ('project_id', models.CharField(default=b'1', max_length=5)),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
            ],
        ),
    ]
