# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-13 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0068_gitlabproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default=b'v1.0.0', max_length=50, verbose_name=b'Tag')),
                ('version', models.CharField(default=b'1.0.0', max_length=50, verbose_name=b'Image Version')),
                ('db_version', models.CharField(default=b'20200101180500', max_length=50, verbose_name=b'DB Version')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='config.GitLabProject', verbose_name=b'Git Project')),
            ],
        ),
    ]
