# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-13 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0069_taginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taginfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='config.GitLabProject', verbose_name=b'Git Project'),
        ),
    ]
