# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-13 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0070_auto_20201213_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitlabproject',
            name='node_name',
            field=models.CharField(default=b'APIGateway', max_length=20, verbose_name=b'Node Name'),
        ),
        migrations.AddField(
            model_name='gitlabproject',
            name='node_type',
            field=models.CharField(choices=[(b'Access', b'Access'), (b'Service', b'Service'), (b'Gateway', b'Gateway'), (b'Consul', b'Consul'), (b'MQ', b'MQ'), (b'APM', b'APM'), (b'Portal', b'Portal'), (b'Mix', b'Mix')], default=b'Service', max_length=20, verbose_name=b'Node Type'),
        ),
    ]
