# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-17 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0072_weixinminiprogramtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weixinminiprogramtemplate',
            name='latest_version',
            field=models.CharField(default=b'', max_length=255, null=True),
        ),
    ]
