# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0073_auto_20201217_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='apigateway',
            name='apm_sample',
            field=models.BooleanField(default=False, verbose_name=b'APM Sample'),
        ),
        migrations.AddField(
            model_name='service',
            name='apm_sample',
            field=models.BooleanField(default=False, verbose_name=b'APM Sample'),
        ),
    ]
