# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2021-01-22 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0074_auto_20201218_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppH5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Portal', max_length=50, verbose_name=b'Portal Name')),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
                ('merge_success', models.BooleanField(default=True, verbose_name=b'Merge Success')),
                ('merge_message', models.CharField(blank=True, default=b'', max_length=500, null=True, verbose_name=b'Merge Message')),
            ],
        ),
    ]
