# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-12-24 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Title', max_length=100, verbose_name=b'Title')),
                ('type', models.CharField(choices=[(b'Doc', b'Doc'), (b'News', b'News')], default=b'Doc', max_length=20)),
                ('url', models.CharField(default=b'https://www.marvelsystem.net', max_length=255, verbose_name=b'Url')),
                ('description', models.CharField(blank=True, default=b'', max_length=1000, verbose_name=b'Description')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name=b'DateTime')),
            ],
        ),
    ]
