# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-09 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default=b'Name', max_length=50, verbose_name=b'CompanyName')),
                ('company_code', models.CharField(default=b'Code', max_length=50, verbose_name=b'CompanyCode')),
                ('description', models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Description')),
            ],
        ),
    ]
