# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-09 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_code',
            field=models.CharField(default=b'Code', max_length=50, verbose_name=b'RegionCode'),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(default=b'Name', max_length=50, verbose_name=b'RegionName'),
        ),
    ]
