# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-01 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='synced',
            field=models.BooleanField(default=True, verbose_name=b'Sync'),
        ),
    ]
