# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-02 02:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_permission_synced'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='APIPermission',
        ),
    ]
