# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-02 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_auto_20201102_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Title', max_length=50, verbose_name=b'Title')),
                ('permission', models.CharField(default=b'Title', max_length=50, verbose_name=b'Permission')),
                ('description', models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Description')),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acl.FunctionPermission', verbose_name=b'children')),
            ],
        ),
    ]
