# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_functionpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionpermission',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='acl.FunctionPermission', verbose_name=b'Parent'),
        ),
    ]
