# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-02 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0005_auto_20201102_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionpermission',
            name='path',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Path'),
        ),
    ]
