# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-02 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0006_functionpermission_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionpermission',
            name='api_permissions',
            field=models.ManyToManyField(blank=True, to='acl.APIPermission', verbose_name=b'API Permissions'),
        ),
    ]
