# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-02 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0007_functionpermission_api_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apipermission',
            old_name='permission',
            new_name='code',
        ),
    ]
