# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0008_auto_20201102_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionpermission',
            name='permission',
        ),
        migrations.AddField(
            model_name='functionpermission',
            name='name',
            field=models.CharField(default=b'Name', max_length=50, verbose_name=b'Name'),
        ),
    ]
