# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0009_auto_20201102_2133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FunctionPermission',
            new_name='Permission',
        ),
        migrations.AlterField(
            model_name='apipermission',
            name='code',
            field=models.IntegerField(default=0, verbose_name=b'Code'),
        ),
    ]
