# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-03 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0010_auto_20201102_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='type',
            field=models.CharField(choices=[(b'Operation', b'Operation'), (b'menu', b'menu'), (b'Page', b'Page')], default=b'menu', max_length=20),
        ),
    ]
