# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-03 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0011_permission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='type',
            field=models.CharField(choices=[(b'Operation', b'Operation'), (b'Menu', b'Menu'), (b'Page', b'Page')], default=b'Menu', max_length=20),
        ),
    ]
