# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-03 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0012_auto_20201103_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='relation',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Relation'),
        ),
    ]
