# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-03 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0014_permission_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='relation',
        ),
        migrations.AddField(
            model_name='permission',
            name='key',
            field=models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Key'),
        ),
    ]
