# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0015_auto_20201103_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='sort',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
