# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-03 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0018_auto_20201103_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='acl.Group', verbose_name=b'Group'),
        ),
    ]
