# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0019_page_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=b'Title', max_length=50, verbose_name=b'Title')),
                ('name', models.CharField(default=b'Name', max_length=50, verbose_name=b'Name')),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('key', models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Key')),
                ('description', models.CharField(blank=True, default=b'', max_length=100, verbose_name=b'Description')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('api_permissions', models.ManyToManyField(blank=True, to='acl.APIPermission', verbose_name=b'API Permissions')),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='page',
            name='type',
        ),
        migrations.AddField(
            model_name='permission',
            name='page',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='acl.Page', verbose_name=b'Page'),
        ),
    ]
