# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-03 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0020_auto_20201103_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['sort']},
        ),
        migrations.RemoveField(
            model_name='page',
            name='api_permissions',
        ),
    ]
