# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-04 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0021_auto_20201103_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(default=b'Icon', max_length=50, verbose_name=b'Icon'),
        ),
    ]
