# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0023_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='enable',
            field=models.BooleanField(default=True, verbose_name=b'Enable'),
        ),
        migrations.AddField(
            model_name='page',
            name='enable',
            field=models.BooleanField(default=True, verbose_name=b'Enable'),
        ),
    ]
