# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2020-11-08 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0024_auto_20201105_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default=b'1.0', max_length=20, verbose_name=b'Version')),
                ('config', models.TextField(verbose_name=b'config')),
                ('env', models.CharField(choices=[(b'Production', b'Production'), (b'Staging', b'Staging'), (b'Development', b'Development')], default=b'Development', max_length=20)),
                ('description', models.TextField(blank=True, default=b'', verbose_name=b'Description')),
                ('md5', models.CharField(default=b'NotSet', max_length=50, verbose_name=b'Md5')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name=b'created time')),
            ],
        ),
    ]
